version: '2'

services:
  mariadb:
    image: mariadb
    restart: always
    expose:
      - "3306"
    env_file:
      - ./env
    networks:
        ttrss_net:
          ipv4_address: 192.168.2.3
    volumes:
      - "/data/docker/volumes/mariadb:/var/lib/mysql"


  ttrss:
    build: .
    restart: always
    depends_on:
      - mariadb
    env_file:
      - ./env
    networks:
        ttrss_net:
          ipv4_address: 192.168.2.2

networks:
    ttrss_net:
      ipam:
        driver: default
        config:
          - subnet: 192.168.2.0/24
